### PR TITLE
Fix some `undefined` types issues

### LINKED ISSUE #407: TypeError: doesn't work if `exactOptionalPropertyTypes:true` in tsconfig.json
`exactOptionalPropertyTypes` just makes type system a little stricter. It is a good to have flag, suggested by [zapatos](https://jawj.github.io/zapatos/).

The error that's currently thrown is:
image

### PR DESCRIPTION
**Pull request by Minigugus**
Fixes #407 `undefined` were missing on optional properties
Fixes #446 `undefined` were not allowed in insert helper calls

Also, it seems that sql fragments were not allowed by types (it's strange that no user have issues with this bug yet :thinking: but it's fixed now anyway)

I don't know if I should run the `build` script for transpilation; some commits where not transpiled, poluting the PR if I commit these changes :confused:

### CODE REVIEW

File: types/index.d.ts [hunk 1]
```diff
@@ -209,17 +209,17 @@ declare namespace postgres {
...
-    internal_position?: string;
-    internal_query?: string;
-    where?: string;
-    schema_name?: string;
-    table_name?: string;
-    column_name?: string;
-    data?: string;
-    type_name?: string;
-    constraint_name?: string;
+    detail?: string | undefined;
```
Comment (ignavan39) [inline types/index.d.ts:212]: expression

```ts
field?: number
``` 
already implies that the type of field

```ts
number | undefined
```

File: types/index.d.ts [hunk 2]
```diff
@@ -285,34 +285,34 @@ declare namespace postgres {
 
   interface Options<T extends PostgresTypeList> extends Partial<BaseOptions<T>> {
     /** @inheritdoc */
-    host?: string;
+    host?: string | undefined;
```
Comment (ignavan39) [inline types/index.d.ts:288]: here is a similar question, why is this?

File: types/index.d.ts [hunk 3]
```diff
@@ -437,21 +437,21 @@ declare namespace postgres {
 
   interface LargeObject {
     writable(options?: {
-      highWaterMark?: number,
-      start?: number
-    }): Promise<Writable>;
+      highWaterMark?: number | undefined,
+      start?: number | undefined
```
Comment (ignavan39) [inline types/index.d.ts:441]: here is a similar question, why is this?
